pip install -U google-genai python-chess -q
pip install -U  openai -q
pip install -U anthropic -q


import chess
import chess.pgn

from google import genai
from google.genai import types
from openai import OpenAI
from anthropic import Anthropic


import json
import re

f = open("g1.srt")
subs = f.read()
print(subs)
f2 = open("g1_cv2.pgn")
game = f2.read()
print(game)


#client = genai.Client(api_key="")#gemini
client = OpenAI(api_key="")
#client = Anthropic(api_key="")
#MODEL_ID = "gemini-3-flash-preview"
MODEL_ID='gpt-5.4'
#MODEL_ID="claude-sonnet-4-6"
#MODEL_ID= "claude-opus-4-6"


json_schema = {
    "type": "object",
    "properties": {
        "moves": {
            "type": "array",
            "description": "An annotated chess game, including subvariations.",
            "items": {
                "type": "object",
                "properties": {
                    "ply": {
                        "type": "integer",
                        "description": "Half-move number."
                    },
                    "san": {
                        "type": "string",
                        "description": "The played move in Standard Algebraic Notation."
                    },
                    "timestamp": {
                        "type": "string",
                        "description": "Timestamp of the move. Use from game comments, NOT from transcript"
                    },
                    "commentary": {
                        "type": "string",
                        "description": "Analysis, key themes, and descriptions of the move."
                    }
                },
                "required": [
                    "ply",
                    "san",
                    "timestamp",
                    "commentary"
                ],
                "additionalProperties": False
            }
        }
    },
    "required": ["moves"],
    "additionalProperties": False
}


prompt = f""" You are given a transcriprion of a chess analysis video, as well as autogenerated pgn of the same analysis.\n
        Transcript has approximate timestamps(hh:mm:ss,ms), and pgn file has also similar timestamps(in seconds) as comments.\n
        Your task is to align relevant commentary from transcript into pgn moves.\n
        Return ONLY valid JSON with move timestamp/SAN notation and the correspondending commentary from video.\n
        You will be evaluated by the information loss, compared to original video.\n
        Your task is to evaluate every move in every variation of game. If something is said about the move,
        include relevant summary to json commentary field. Otherwise, add comment 'skip'  \n
        Transcript:{subs}\n
        Moves: {game}\n"""

#config = types.GenerateContentConfig( # gemini
#    response_mime_type="application/json",
#    response_schema=json_schema)

#response = client.models.generate_content( #gemini
#    model=MODEL_ID,
#    contents=prompt,
#    config=config
#)

response = client.chat.completions.create( #GPT
#response = client.messages.create(#claude
    model=MODEL_ID,
   # max_tokens=16000, #claude only
    messages=[
        {
            "role": "user",
            "content": prompt,
        }
    ],
    response_format={ # gpt
      "type": "json_schema",
      "json_schema": {
          "name": "my_response",
          "strict": True,
          "schema": json_schema,
      },
    }
   # output_config={ #claude standard
    #    "format": {
     #       "type": "json_schema",
      #      "schema": json_schema,
       # }
    #},
)

#with client.messages.stream( # use with claude if over hour input
    #model=MODEL_ID,
    #max_tokens=128000,
    #messages=[
     #   {"role": "user", "content": prompt}
    #],
    #output_config={
     #   "format": {
    #        "type": "json_schema",
   #         "schema": json_schema,
  #      }
 #   },
#) as stream:
#    response = stream.get_final_message()

#print(response.content[0])
print(response.choices[0].message.content)

import json
import chess.pgn

data = json.loads(response.choices[0].message.content)["moves"] # gpt
#data = json.loads(response.content[0].text)["moves"] # claude

with open('g1_cv2.pgn') as pgn_file:
    game = chess.pgn.read_game(pgn_file)
board = game.board()
from typing import List, Dict, Optional, Tuple

def traverse_all_variations(game: chess.pgn.Game) -> List[Dict]:

    all_moves = []

    def traverse_node(node: chess.pgn.ChildNode, board: chess.Board,
                      path: List[str], variation_id: int = 0,
                      depth: int = 0, parent_ply: int = 0):



        if node.is_end():
            return

        # Process all variations
        for idx, child in enumerate(node.variations):
            move = child.move
            san = board.san(move)
            current_ply = board.ply() + 1


            move_data = {
                'san': san,
                'comment': child.comment if child.comment else '',
            }
            key = child.comment + "_" + san
            if(key in comments):
              if(comments[key]) != 'skip':
                child.comment = comments[key]
              else:
                child.comment = ''


            all_moves.append(move_data)

            # Recursively traverse this child's variations
            new_board = board.copy()
            new_board.push(move)
            traverse_node(child, new_board, path + [san],
                         f"{variation_id}_{idx}", depth + 1, current_ply)

    # Start traversal from the root
    board = game.board()
    traverse_node(game, board, [], "0", 0, 0)

    return all_moves
comments= {}
for item in data:
  if 'timestamp' in item and 'san' in item:
    key = str(item['timestamp']) + '_' + str(item['san'])
    comments[key] = item['commentary']
print(len(comments))
print(comments)


variations =traverse_all_variations(game)
print(len(variations))

#save game:
with open('g1.pgn', "w") as f:
  exporter = chess.pgn.FileExporter(f)
  game.accept(exporter)
